[project]
name = "ldaca-loader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dataclasses>=0.8",
    "jupyter>=1.1.1",
    "notebook>=7.4.7",
    "pandas>=2.3.3",
    "pytest>=9.0.2",
    "pytest-localserver>=0.9.0.post0",
    "requests>=2.32.5",
    "rocrate-tabular",
]

[tool.uv.sources]
rocrate-tabular = { git = "https://github.com/Sydney-Informatics-Hub/rocrate-tabular.git" }
