[project]
name = "ldaca-loader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.4.7",
    "pandas>=2.3.3",
    "polar>=0.0.127",
    "requests>=2.32.5",
    "rocrate-tabular",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
rocrate-tabular = { git = "https://github.com/Atiq0452/rocrate-tabular.git" }
